Repository jenkinsci/idea-stapler-plugin, pull requests merged in 2022-10, with the labels that each got.

#114 Override organization issue template for a Bug
  .github/ISSUE_TEMPLATE/1-report-bug.yml
Labels: internal, Hacktoberfest

#116 Bump gradlew to 7.5.1
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: internal, Hacktoberfest

#115 Fix "IllegalArgumentException: Invalid range specified: (1, -1)" when editing `style` attribute in Jelly files
  build.gradle
  gradle.properties
  src/main/java/org/kohsuke/stapler/idea/JellyLanguageInjector.java
Labels: bug, Hacktoberfest

#112 A file template is added for a Stapler Jelly View
  src/main/resources/fileTemplates/Jenkins Jelly view.jelly.ft
Labels: enhancement, Hacktoberfest

#118 Avoid hardcoding releases to verify agains, by using JetBrains Gradle plugin feature that lists the releases
  build.gradle
  gradle.properties
  src/main/java/org/kohsuke/stapler/idea/icons/Icons.java
Labels: pipeline, Hacktoberfest

#113 Show Views in the Class' Structure tool window
  build.gradle
  src/main/java/org/kohsuke/stapler/idea/extension/AbstractStructureViewExtension.java
  src/main/java/org/kohsuke/stapler/idea/extension/JavaStructureViewExtension.java
  src/main/java/org/kohsuke/stapler/idea/extension/JellyStructureViewExtension.java
  src/main/java/org/kohsuke/stapler/idea/icons/Icons.java
  src/main/java/org/kohsuke/stapler/idea/language/JellyFileType.java
  src/main/java/org/kohsuke/stapler/idea/language/JellyLanguage.java
  src/main/java/org/kohsuke/stapler/idea/language/JellyParserDefinition.java
  src/main/java/org/kohsuke/stapler/idea/psi/JellyFile.java
  src/main/java/org/kohsuke/stapler/idea/psi/JellyFileImpl.java
  src/main/java/org/kohsuke/stapler/idea/psi/link/LinkJellyFileImpl.java
  src/main/java/org/kohsuke/stapler/idea/structureview/LeafJellyFileTreeElement.java
  src/main/java/org/kohsuke/stapler/idea/structureview/LeafPsiClassTreeElement.java
  src/main/resources/META-INF/plugin.xml
  src/main/resources/org/kohsuke/stapler/idea/icons/jelly.svg
  src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: major-enhancement, Hacktoberfest, bump-minor, Hacktoberfest-accepted
